//! Tauri 2 runtime entry point, gated behind the `tauri-runtime` feature.
//!
//! Only compiled when the optional `tauri-runtime` Cargo feature is enabled
//! (it pulls in Tauri 2 itself plus the official plugins). With the feature
//! off — the default for CI / library consumers — this module is a no-op
//! placeholder so the `pub mod runtime;` declaration in `lib.rs` resolves
//! and `cargo fmt --all` succeeds.
//!
//! The real Tauri shell will land here in a follow-on slice once GA
//! desktop-signing CI is in place; until then the desktop binary's
//! runtime entry point is generated by the `tauri::Builder` directly in
//! its own `main.rs` (see `apps/gaussclaw-desktop/src-tauri/`).

/// Marker function that ties this module to the runtime feature gate.
/// Not exported; kept so `cargo doc` finds the module non-empty.
#[allow(dead_code)]
fn _runtime_feature_present() {}
